name: CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run:
          go get matchMaker

      - name: Run build
        run: go build -v

      - name: Run tests
        run: go test -v
