name: CI

on:
  # This workflow should only run when there are pushes to the main branches as this displays on the ReadMe.md file
  # Any deployment integrations should also go in this workflow
  push:
    branches:
      - main
      - master
      - develop
      - feature/*
jobs:
  build:
  # This will run it on multiple os's listed in the matrix
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        # This will install everything in the go.mod file
        run: go get matchMaker

      - name: Run build
        # This will provide a detailed log output of the new builds that are incomplete
        run: go build -v
        # This will build everything again, log it out and log the working directory
        #run: go build -a -v -work

      - name: Run tests
        # This will provide detailed test logs for each individual test
        run: go test -v
